'use client'

import { AuthContextProvider } from './context/Auth.Context'
import { FeatureFlagContextProvider } from './context/FeatureFlags.Context'
import '../globals.css'
import { dir } from 'i18next'
import { useTranslation } from 'app/i18n/client'
import { fallbackLng, languages } from 'app/i18n/settings'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// export async function generateStaticParams() {
//     return languages.map((lng) => ({ lng }));
// }

export default function RootLayout({ children, params: { lng } }) {
  if (languages.indexOf(lng) < 0) lng = fallbackLng
  const { t } = useTranslation(lng)

  return (
    <html lang={lng} dir={dir(lng)}>
      <head>
        <link href='https://assets.calendly.com/assets/external/widget.css' rel='stylesheet' />
        <script src='https://assets.calendly.com/assets/external/widget.js' type='text/javascript' async></script>
        <script src='https://tally.so/widgets/embed.js' async></script>
      </head>

      <body className={inter.className}>
        <AuthContextProvider>
          <FeatureFlagContextProvider>
            {/* <NavBar /> */}
            {children}
          </FeatureFlagContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
